# Generated by Django 4.2.2 on 2024-11-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_image_alter_user_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
